name: Maven Build

on:
  push:
    branches: [ "master", "main", "add-maven" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "main", "add-maven" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maven-build-artifacts
        path: target/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
